platform:
- x86
- x64
environment:
  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "6"
cache:
- 'node_modules'

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g npm@3
- set PATH=%APPDATA%\npm;%PATH%
- npm install

test_script:
- node --version
- npm --version
- ps: |
      if (($env:nodejs_version -eq "0.10") -or ($env:nodejs_version -eq "0.12")) {
        npm run internCI
      } else {
        npm run ci
      }

build: off
