os:
- linux
- osx
osx_image: xcode8
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
cache:
  directories:
  - node_modules
env:
  global:
  - CODECLIMATE_REPO_TOKEN=f38fa2f1de8a3a776fe3587f9eef2df022f9822241563e4df82cbc9ab3d7997b
script:
- |
  if [[ ${TRAVIS_NODE_VERSION:0:1} = "0" ]]; then
    npm run oldNodeCI
  else
    npm run ci
  fi
